# Generated by Django 4.2.5 on 2023-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
